// src/services/bolt.js
// BoltService — bolt.new platform integration
// Bolt Studio Pro

import { BaseService } from './base.js';

const BOLT_PROJECTS = [
  { id: 'proj_bolt_001', name: 'E-commerce Dashboard',    stack: 'react',   createdAt: '2026-04-10T09:00:00Z', status: 'active'   },
  { id: 'proj_bolt_002', name: 'Portfolio Builder',       stack: 'vue',     createdAt: '2026-04-18T14:30:00Z', status: 'active'   },
  { id: 'proj_bolt_003', name: 'Auth Starter Kit',        stack: 'svelte',  createdAt: '2026-05-01T11:15:00Z', status: 'archived' },
  { id: 'proj_bolt_004', name: 'AI Chat Interface',       stack: 'react',   createdAt: '2026-05-20T08:45:00Z', status: 'active'   },
];

export class BoltService extends BaseService {
  constructor(credential) {
    super('Bolt', {
      baseUrl: 'https://api.bolt.new/v1',
      ...credential,
    });

    this._session = null;
    this._credits = credential?.credits ?? 2500;
  }

  // ─── Send Prompt ─────────────────────────────────────────────────────────────

  async sendPrompt(prompt, projectId = null) {
    if (!prompt || typeof prompt !== 'string') {
      throw Object.assign(new Error('BoltService: prompt must be a non-empty string'), { code: 'INVALID_INPUT' });
    }

    const body = {
      prompt,
      projectId: projectId || `proj_bolt_${Date.now()}`,
      model:     'bolt-v2',
      stream:    false,
    };

    const res = await this.request('/prompt', {
      method: 'POST',
      body:   JSON.stringify(body),
      _mockData: {
        id:          `resp_${Date.now()}`,
        projectId:   body.projectId,
        prompt,
        response: {
          text:       `[Bolt] Generated response for: "${prompt.slice(0, 60)}..."`,
          files:      [
            { path: 'src/App.jsx',   content: '// Generated by Bolt\nexport default function App() { return <div>Hello</div>; }' },
            { path: 'package.json',  content: '{"name":"bolt-project","version":"1.0.0"}' },
          ],
          tokensUsed: Math.floor(prompt.length * 1.4),
        },
        model:     body.model,
        createdAt: new Date().toISOString(),
      },
    });

    // Deduct simulated credits
    const used = Math.ceil(prompt.length * 0.1);
    this._credits = Math.max(0, this._credits - used);

    return res.data;
  }

  // ─── Projects ────────────────────────────────────────────────────────────────

  async getProjects() {
    const res = await this.request('/projects', {
      _mockData: {
        projects: BOLT_PROJECTS,
        total:    BOLT_PROJECTS.length,
      },
    });
    return res.data;
  }

  async createProject(name) {
    if (!name) throw Object.assign(new Error('BoltService: project name required'), { code: 'INVALID_INPUT' });

    const project = {
      id:        `proj_bolt_${Date.now()}`,
      name,
      stack:     'react',
      status:    'active',
      createdAt: new Date().toISOString(),
      url:       `https://bolt.new/project/${name.toLowerCase().replace(/\s+/g, '-')}`,
    };

    const res = await this.request('/projects', {
      method: 'POST',
      body:   JSON.stringify({ name }),
      _mockData: { project },
    });

    BOLT_PROJECTS.unshift(project);
    return res.data;
  }

  // ─── Credits ─────────────────────────────────────────────────────────────────

  async getCredits() {
    const res = await this.request('/credits', {
      _mockData: {
        credits:     this._credits,
        limit:       5000,
        resetAt:     new Date(Date.now() + 86_400_000).toISOString(),
        plan:        'pro',
        percentUsed: Math.round(((5000 - this._credits) / 5000) * 100),
      },
    });
    return res.data;
  }

  // ─── Session ─────────────────────────────────────────────────────────────────

  async getSessionStatus() {
    const now = new Date();

    if (!this._session) {
      this._session = {
        id:        `sess_bolt_${Date.now()}`,
        userId:    this.credential?.userId || 'user_anon',
        createdAt: now.toISOString(),
        expiresAt: new Date(now.getTime() + 3_600_000).toISOString(),
        active:    true,
        platform:  'bolt.new',
      };
    }

    const res = await this.request('/session', {
      _mockData: { session: this._session },
    });

    return res.data;
  }
}
