// src/services/lovable.js
// LovableService — Lovable platform integration
// Bolt Studio Pro

import { BaseService } from './base.js';

const LOVABLE_PROJECTS = [
  { id: 'lv_proj_001', name: 'SaaS Landing Page',   framework: 'react',   updatedAt: '2026-05-28T10:00:00Z' },
  { id: 'lv_proj_002', name: 'Admin Panel Template', framework: 'react',   updatedAt: '2026-05-25T08:30:00Z' },
  { id: 'lv_proj_003', name: 'Blog CMS',             framework: 'next.js', updatedAt: '2026-05-15T16:00:00Z' },
];

export class LovableService extends BaseService {
  constructor(credential) {
    super('Lovable', {
      baseUrl: 'https://api.lovable.dev/v1',
      ...credential,
    });

    this._token      = credential?.token   || `lv_tok_${Math.random().toString(36).slice(2)}`;
    this._tokenExpiry = Date.now() + 3_600_000;
    this._usageStats = { promptsUsed: 0, componentsGenerated: 0, limit: 500 };
  }

  // ─── Token Management ────────────────────────────────────────────────────────

  async refreshToken() {
    const res = await this.request('/auth/refresh', {
      method: 'POST',
      body:   JSON.stringify({ token: this._token }),
      _mockData: {
        token:     `lv_tok_${Math.random().toString(36).slice(2)}`,
        expiresIn: 3600,
        issuedAt:  new Date().toISOString(),
      },
    });

    this._token       = res.data.token;
    this._tokenExpiry = Date.now() + res.data.expiresIn * 1000;
    this.credential.token = this._token;

    return res.data;
  }

  _ensureToken() {
    if (Date.now() >= this._tokenExpiry - 30_000) {
      return this.refreshToken();
    }
    return Promise.resolve();
  }

  // ─── Send Prompt ─────────────────────────────────────────────────────────────

  async sendPrompt(prompt) {
    if (!prompt) throw Object.assign(new Error('LovableService: prompt required'), { code: 'INVALID_INPUT' });

    await this._ensureToken();

    this._usageStats.promptsUsed++;

    const res = await this.request('/generate', {
      method: 'POST',
      body:   JSON.stringify({ prompt, token: this._token }),
      _mockData: {
        id:        `lv_gen_${Date.now()}`,
        prompt,
        output: {
          component: `// Lovable generated\nexport default function Component() {\n  return <div className="lovable">${prompt.slice(0, 30)}</div>;\n}`,
          styles:    `.lovable { font-family: sans-serif; padding: 1rem; }`,
          preview:   `https://preview.lovable.dev/${Date.now()}`,
        },
        tokensUsed: Math.ceil(prompt.length * 1.2),
        createdAt:  new Date().toISOString(),
      },
    });

    return res.data;
  }

  // ─── Projects ────────────────────────────────────────────────────────────────

  async getProjects() {
    await this._ensureToken();

    const res = await this.request('/projects', {
      _mockData: {
        projects: LOVABLE_PROJECTS,
        total:    LOVABLE_PROJECTS.length,
      },
    });

    return res.data;
  }

  // ─── Create Component ─────────────────────────────────────────────────────────

  async createComponent(spec = {}) {
    if (!spec.name) throw Object.assign(new Error('LovableService: spec.name required'), { code: 'INVALID_INPUT' });

    await this._ensureToken();
    this._usageStats.componentsGenerated++;

    const component = {
      id:          `lv_comp_${Date.now()}`,
      name:        spec.name,
      type:        spec.type    || 'functional',
      framework:   spec.framework || 'react',
      props:       spec.props   || [],
      code:        `// ${spec.name} — generated by Lovable\nexport default function ${spec.name}({ ${(spec.props || []).join(', ')} }) {\n  return <div>{/* ${spec.name} content */}</div>;\n}`,
      createdAt:   new Date().toISOString(),
      previewUrl:  `https://preview.lovable.dev/components/${Date.now()}`,
    };

    const res = await this.request('/components', {
      method: 'POST',
      body:   JSON.stringify({ spec, token: this._token }),
      _mockData: { component },
    });

    return res.data;
  }

  // ─── Usage ───────────────────────────────────────────────────────────────────

  async getUsage() {
    const res = await this.request('/usage', {
      _mockData: {
        ...this._usageStats,
        percentUsed:        Math.round((this._usageStats.promptsUsed / this._usageStats.limit) * 100),
        resetDate:          new Date(Date.now() + 7 * 86_400_000).toISOString(),
        plan:               'growth',
      },
    });

    return res.data;
  }
}
