FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json .
COPY apps/api/package*.json apps/api/
COPY packages/shared/package*.json packages/shared/
RUN npm ci
COPY . .
RUN npm run build:api

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/apps/api/package*.json .
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4000
CMD ["node", "dist/main.js"]
