export type SocketClientToServerEvent =
  | 'auth.resume'
  | 'device:join'
  | 'session.create'
  | 'session.join'
  | 'session.leave'
  | 'session.signal'
  | 'session.ice-restart-request'
  | 'session:request'
  | 'session:join'
  | 'session:leave'
  | 'session:accepted'
  | 'session:denied'
  | 'session:ended'
  | 'session:emergency_stop'
  | 'webrtc:offer'
  | 'webrtc:answer'
  | 'webrtc:ice_candidate'
  | 'webrtc:connection_state'
  | 'audit.emit'
  | 'support.bundle-ready';

export type SocketServerToClientEvent =
  | 'auth.accepted'
  | 'auth.rejected'
  | 'device:joined'
  | 'device:online'
  | 'device:offline'
  | 'session.created'
  | 'session.joined'
  | 'session.peer-joined'
  | 'session.peer-left'
  | 'session.signal'
  | 'session.ice-restart-requested'
  | 'session.ended'
  | 'session:requested'
  | 'session:joined'
  | 'session:peer_joined'
  | 'session:peer_left'
  | 'session:accepted'
  | 'session:denied'
  | 'session:ended'
  | 'session:emergency_stop'
  | 'webrtc:offer'
  | 'webrtc:answer'
  | 'webrtc:ice_candidate'
  | 'webrtc:connection_state'
  | 'webrtc:error'
  | 'billing.limit-hit'
  | 'security.event';

export type SocketEventName = SocketClientToServerEvent | SocketServerToClientEvent;
