import { z } from 'zod';

export const BiometricType = z.enum([
  'fingerprint',
  'face_id',
  'iris_scan',
  'other',
]);

export const BiometricAuthRequestSchema = z.object({
  userId: z.string().uuid().describe('ID of the user attempting biometric authentication.'),
  deviceIdentifier: z.string().min(1).describe('Unique identifier for the mobile device.'),
  biometricType: BiometricType.describe('Type of biometric used for authentication.'),
  challenge: z.string().min(1).describe('Cryptographic challenge provided by the server.'),
  signature: z.string().min(1).describe('Cryptographic signature generated by the device using biometric data.'),
  timestamp: z.string().datetime().describe('Timestamp of the authentication request.'),
});

export type BiometricAuthRequest = z.infer<typeof BiometricAuthRequestSchema>;

export const BiometricAuthResponseSchema = z.object({
  success: z.boolean().describe('Indicates if the biometric authentication was successful.'),
  message: z.string().optional().describe('A message detailing the outcome of the authentication.'),
  token: z.string().optional().describe('Authentication token if successful.'),
  errorCode: z.string().optional().describe('Error code if authentication failed.'),
});

export type BiometricAuthResponse = z.infer<typeof BiometricAuthResponseSchema>;

export const MfaEnrollmentRequestSchema = z.object({
  userId: z.string().uuid().describe('ID of the user enrolling for MFA.'),
  deviceIdentifier: z.string().min(1).describe('Unique identifier for the mobile device.'),
  biometricType: BiometricType.describe('Type of biometric being enrolled.'),
  publicKey: z.string().min(1).describe('Public key generated by the device for biometric verification.'),
  challenge: z.string().min(1).describe('Cryptographic challenge for enrollment verification.'),
  signature: z.string().min(1).describe('Cryptographic signature for enrollment verification.'),
  timestamp: z.string().datetime().describe('Timestamp of the enrollment request.'),
});

export type MfaEnrollmentRequest = z.infer<typeof MfaEnrollmentRequestSchema>;

export const MfaEnrollmentResponseSchema = z.object({
  success: z.boolean().describe('Indicates if the MFA enrollment was successful.'),
  message: z.string().optional().describe('A message detailing the outcome of the enrollment.'),
  enrollmentId: z.string().uuid().optional().describe('ID of the successful MFA enrollment.'),
  errorCode: z.string().optional().describe('Error code if enrollment failed.'),
});

export type MfaEnrollmentResponse = z.infer<typeof MfaEnrollmentResponseSchema>;
