import { z } from 'zod';

export const RootCauseCategory = z.enum([
  'software_bug',
  'infrastructure_failure',
  'configuration_error',
  'network_issue',
  'dependency_failure',
  'resource_exhaustion',
  'security_incident',
  'human_error',
  'external_factor',
  'unknown',
]);

export const RootCauseAnalysisResultSchema = z.object({
  id: z.string().uuid().describe('Unique identifier for the root cause analysis result.'),
  incidentId: z.string().uuid().describe('ID of the incident for which RCA was performed.'),
  analysisTimestamp: z.string().datetime().describe('Timestamp when the analysis was completed.'),
  identifiedRootCause: RootCauseCategory.describe('The primary category of the identified root cause.'),
  detailedExplanation: z.string().min(1).describe('Detailed explanation of the root cause and contributing factors.'),
  confidenceScore: z.number().min(0).max(1).optional().describe('Confidence score of the identified root cause (0-1).'),
  suggestedRemediation: z.string().optional().describe('Suggested actions to remediate the root cause.'),
  relatedEvents: z.array(z.string().uuid()).optional().describe('List of IDs of related events or alerts.'),
  analyzedMetrics: z.record(z.string(), z.any()).optional().describe('Key metrics and their values analyzed during RCA.'),
  analyzedLogs: z.array(z.string()).optional().describe('Snippets or references to relevant log entries.'),
  createdByAi: z.boolean().default(true).describe('Indicates if the RCA was primarily generated by AI.'),
  createdAt: z.string().datetime().optional().describe('Timestamp when the RCA result was created.'),
  updatedAt: z.string().datetime().optional().describe('Timestamp when the RCA result was last updated.'),
});

export type RootCauseAnalysisResult = z.infer<typeof RootCauseAnalysisResultSchema>;

export const CreateRootCauseAnalysisResultSchema = RootCauseAnalysisResultSchema.omit({ id: true, createdAt: true, updatedAt: true });
export type CreateRootCauseAnalysisResult = z.infer<typeof CreateRootCauseAnalysisResultSchema>;

export const UpdateRootCauseAnalysisResultSchema = RootCauseAnalysisResultSchema.partial().extend({
  id: z.string().uuid(),
});
export type UpdateRootCauseAnalysisResult = z.infer<typeof UpdateRootCauseAnalysisResultSchema>;
