// .agents/skills/bulk_code_writer/scripts/generate.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REACT_BASE = path.join(__dirname, '../../../../src');
const componentsDir = path.join(REACT_BASE, 'components/generated');
const libDir = path.join(REACT_BASE, 'lib/generated');

// Create directories if they don't exist
fs.mkdirSync(componentsDir, { recursive: true });
fs.mkdirSync(libDir, { recursive: true });

console.log('Generating 75 component files and 75 utility files (150 total)...');

// 1. Generate 75 React Component files
for (let i = 1; i <= 75; i++) {
  const padIndex = String(i).padStart(3, '0');
  const filename = `feat_comp_${padIndex}.jsx`;
  const filePath = path.join(componentsDir, filename);

  const content = `import React from 'react';

/**
 * Autogenerated Feature Component #${padIndex}
 */
export function FeatureComponent_${padIndex}() {
  const [val, setVal] = React.useState(0);
  
  return (
    <div className="p-4 border rounded bg-slate-800 text-slate-100 shadow-sm" id="feat_comp_${padIndex}">
      <h5 className="font-semibold text-lg">Feature Component ${padIndex}</h5>
      <p className="text-sm text-slate-300 my-2">State count value: {val}</p>
      <button 
        onClick={() => setVal(v => v + 1)} 
        className="px-3 py-1 bg-blue-600 hover:bg-blue-700 text-white rounded text-xs transition-colors"
      >
        Increment (${padIndex})
      </button>
    </div>
  );
}
`;

  fs.writeFileSync(filePath, content, 'utf8');
}

// 2. Generate 75 ES6 Utility files
for (let i = 1; i <= 75; i++) {
  const padIndex = String(i).padStart(3, '0');
  const filename = `feat_util_${padIndex}.js`;
  const filePath = path.join(libDir, filename);

  const content = `/**
 * Autogenerated Utility Module #${padIndex}
 */

export function calculateMetrics_${padIndex}(dataArray) {
  if (!Array.isArray(dataArray)) return { sum: 0, count: 0, average: 0 };
  
  const sum = dataArray.reduce((acc, curr) => acc + (typeof curr === 'number' ? curr : 0), 0);
  const count = dataArray.length;
  const average = count > 0 ? sum / count : 0;
  
  return {
    sum,
    count,
    average,
    timestamp: new Date().toISOString()
  };
}

export function formatFeatureMessage_${padIndex}(name, detail) {
  return \`[Feature ${padIndex}] \${name}: \${detail}\`;
}
`;

  fs.writeFileSync(filePath, content, 'utf8');
}

console.log('Success: 150 files generated under src/components/generated/ and src/lib/generated/');
